In [1]:
print("Welcome to AI Powered Fake News Detection Project")

Welcome to AI Powered Fake News Detection Project

In [2]:
project_name = "AI Powered Fake News Detection"
print(project_name)

AI Powered Fake News Detection

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("../data/WELFake_Dataset.csv")

In [5]:
data.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [6]:
data.shape

(72134, 4)

In [7]:
data.columns

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='str')

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  72134 non-null  int64
 1   title       71576 non-null  str
 2   text        72095 non-null  str
 3   label       72134 non-null  int64
dtypes: int64(2), str(2)
memory usage: 2.2 MB

In [9]:
data.isnull().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [10]:
data = data.dropna()

In [11]:
data.shape

(71537, 4)

In [12]:
data.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [13]:
data = data.drop(columns=['Unnamed: 0'])

In [14]:
data.head()

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1
5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1

In [15]:
data.duplicated().sum()

np.int64(8416)

In [16]:
data = data.drop_duplicates()

In [17]:
data.duplicated().sum()

np.int64(0)

In [18]:
data.shape

(63121, 3)

In [19]:
data['label'].value_counts()

label
0    34791
1    28330
Name: count, dtype: int64

In [20]:
data['content'] = data['title'] + " " + data['text']

In [21]:
data.head()

,title,text,label,content
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1,LAW ENFORCEMENT ON HIGH ALERT Following Threat...
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0,"Bobby Jindal, raised Hindu, uses story of Chri..."
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1,SATAN 2: Russia unvelis an image of its terrif...
5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1,About Time! Christian Group Sues Amazon and SP...

In [22]:
import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [23]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [24]:
ps = PorterStemmer()

In [25]:
print(stopwords.words('english')[:20])

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']

In [26]:
sample = "Hello!!! My name is Raj. I am 20 years old."
print(sample)

Hello!!! My name is Raj. I am 20 years old.

In [27]:
re.sub('[^a-zA-Z]', ' ', sample)

'Hello    My name is Raj  I am    years old '

In [38]:
def preprocess_text(text):

    review = re.sub('[^a-zA-Z]', ' ', str(text))

    review = review.lower()

    review = review.split()

    review = [ps.stem(word) for word in review if word not in stop_words]

    review = " ".join(review)

    return review

In [29]:
sample = "Hello!!! My name is Raj. I am playing Cricket every day."

preprocess_text(sample)

'hello name raj play cricket everi day'

In [36]:
data['content'] = data['content'].apply(preprocess_text)

KeyboardInterrupt:

In [40]:
stop_words = set(stopwords.words('english'))

In [35]:
stop_words = set(stopwords.words('english'))

In [42]:
data['content'] = data['content'].apply(preprocess_text)

In [41]:
data['content'].head().apply(preprocess_text)

0    law enforc high alert follow threat cop white ...
2    unbeliev obama attorney gener say charlott rio...
3    bobbi jindal rai hindu use stori christian con...
4    satan russia unv imag terrifi new supernuk wes...
5    time christian group sue amazon splc design ha...
Name: content, dtype: str

In [43]:
 len(data)

63121

In [44]:
data['content'].iloc[0]

'law enforc high alert follow threat cop white blacklivesmatt fyf terrorist video comment expect barack obama member fyf fukyoflag blacklivesmatt movement call lynch hang white peopl cop encourag radio show tuesday night turn tide kill white peopl cop send messag kill black peopl america one f yoflag organ call sunshin radio blog show host texa call sunshin f ing opinion radio show snapshot fyf lolatwhitefear twitter page p show urg support call fyf tonight continu dismantl illu white snapshot twitter radio call invit fyf radio show air p eastern standard time show caller clearli call lynch kill white peopl minut clip radio show heard provid breitbart texa someon would like refer hannib alreadi receiv death threat result interrupt fyf confer call unidentifi black man said mother f ker start f ing like us bunch ni er takin one us roll said cau alreadi roll gang anyway six seven black mother f cker see white person lynch ass let turn tabl conspir cop start lose peopl state emerg specul one two thing would happen big ass r war ni er go start backin alreadi get kill f k got lose sunshin could heard say yep true f king true said need turn tabl kid get shot somebodi need becom sacrif side said everybodi whatev like say everybodi differ posit war continu give f k anyway said might well util turn tabl n er said way start lookin like havin mani casualti causal side instead kill black peopl black live matter mother f ker got make matter find mother f ker alon snap ass f hang damn tree take pictur send mother f ker need one exampl peopl start watchin turn tabl said said start trickl effect said one white person hung flat hang start trickl effect continu black peopl good start trend said get upper hand anoth black man spoke say need kill cop kill us first black male said best method right breitbart texa previou report sunshin upset racist white peopl infiltr disrupt one confer call subsequ relea phone number one infiltr veteran immedi start receiv threaten call one f yoflag movement support allegedli told veteran infiltr publicli post confer call go rape gut pregnant wife f ing piec sh unborn creatur hung tree breitbart texa previou encount sunshin sandra bland protest waller counti jail texa said white peopl kill told journalist photograph see nappi ass hair head mean one milit negro said protest redneck mother f ker murder sandra bland nappi hair like fyf black radic say hold imperi power actual respon terrorist attack septemb th account day report breitbart texa sever websit twitter handl movement palmetto star describ one head organ said youtub video support burn symbol illu superior fal white supremaci like american flag british flag polic uniform ku klux klan hood sierra mcgrone nocturnu libertu post help young afrikan clean rag oppress post two photo one appear photo black man wipe nake butt american flag entir stori breitbart news'

In [45]:
import time

start = time.time()

data_small = data.head(1000).copy()
data_small['content'] = data_small['content'].apply(preprocess_text)

print("Completed in:", time.time() - start, "seconds")

Completed in: 12.1743745803833 seconds

In [46]:
!pip install tqdm

Requirement already satisfied: tqdm in C:\Users\HP\anaconda3\envs\fake_news_env\Lib\site-packages (4.69.1)
Requirement already satisfied: colorama in C:\Users\HP\anaconda3\envs\fake_news_env\Lib\site-packages (from tqdm) (0.4.6)

In [47]:
from tqdm import tqdm

tqdm.pandas()

In [48]:
data['content'] = data['content'].progress_apply(preprocess_text)

100%|██████████| 63121/63121 [17:09<00:00, 61.34it/s]

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(data['content']).toarray()

y = data['label']

In [50]:
print(X.shape)
print(y.shape)

(63121, 5000)
(63121,)

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [52]:
print(X_train.shape)
print(X_test.shape)

(50496, 5000)
(12625, 5000)

In [53]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [54]:
y_pred = model.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9436831683168316

In [56]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95      6955
           1       0.94      0.94      0.94      5670

    accuracy                           0.94     12625
   macro avg       0.94      0.94      0.94     12625
weighted avg       0.94      0.94      0.94     12625

In [57]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[6606  349]
 [ 362 5308]]

In [60]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(tfidf, open("tfidf.pkl", "wb"))

print("Model Saved Successfully")

Model Saved Successfully

In [61]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(tfidf, open("tfidf.pkl", "wb"))

print("Model Saved Successfully")

Model Saved Successfully

In [62]:
import os
import pickle

os.makedirs("models", exist_ok=True)

with open("models/model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("models/tfidf.pkl", "wb") as f:
    pickle.dump(tfidf, f)

print("✅ Saved Successfully")

✅ Saved Successfully

In [63]:
import os
import pickle

os.makedirs("models", exist_ok=True)

with open("models/model.pkl", "wb") as f:
    pickle.dump(model, f)

with open("models/tfidf.pkl", "wb") as f:
    pickle.dump(tfidf, f)

print("✅ Model Saved Successfully")

✅ Model Saved Successfully

In [64]:
import os
print(os.getcwd())

C:\Users\HP\OneDrive\Desktop\Fake_News_Detection\notebooks

In [65]:
import os
import pickle

save_path = "../models"

os.makedirs(save_path, exist_ok=True)

with open(os.path.join(save_path, "model.pkl"), "wb") as f:
    pickle.dump(model, f)

with open(os.path.join(save_path, "tfidf.pkl"), "wb") as f:
    pickle.dump(tfidf, f)

print("✅ Saved in Root Models Folder")

✅ Saved in Root Models Folder

In [66]:
print(df.head())
print(df.columns)
print(df["label"].value_counts())

NameError: name 'df' is not defined

In [67]:
import pandas as pd

df = pd.read_csv("../data/WELFake_Dataset.csv")

print(df.head())
print(df.columns)

   Unnamed: 0                                              title  \
0           0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1           1                                                NaN
2           2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3           3  Bobby Jindal, raised Hindu, uses story of Chri...
4           4  SATAN 2: Russia unvelis an image of its terrif...

                                                text  label
0  No comment is expected from Barack Obama Membe...      1
1     Did they post their votes for Hillary already?      1
2   Now, most of the demonstrators gathered last ...      1
3  A dozen politically active pastors came here f...      0
4  The RS-28 Sarmat missile, dubbed Satan 2, will...      1
Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='str')

In [68]:
print(df["label"].value_counts())

label
1    37106
0    35028
Name: count, dtype: int64

In [69]:
print(df[df["label"] == 0][["title", "text"]].head(5))

                                                title  \
3   Bobby Jindal, raised Hindu, uses story of Chri...
11  May Brexit offer would hurt, cost EU citizens ...
12  Schumer calls on Trump to appoint official to ...
14  No Change Expected for ESPN Political Agenda D...
15  Billionaire Odebrecht in Brazil scandal releas...

                                                 text
3   A dozen politically active pastors came here f...
11  BRUSSELS (Reuters) - British Prime Minister Th...
12  WASHINGTON (Reuters) - Charles Schumer, the to...
14  As more and more sports fans turn off ESPN to ...
15  RIO DE JANEIRO/SAO PAULO (Reuters) - Billionai...

In [70]:
print(df[df["label"] == 1][["title", "text"]].head(5))

                                               title  \
0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1                                                NaN
2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
4  SATAN 2: Russia unvelis an image of its terrif...
5  About Time! Christian Group Sues Amazon and SP...

                                                text
0  No comment is expected from Barack Obama Membe...
1     Did they post their votes for Hillary already?
2   Now, most of the demonstrators gathered last ...
4  The RS-28 Sarmat missile, dubbed Satan 2, will...
5  All we can say on this one is it s about time ...

In [71]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))

Accuracy : 0.9436831683168316

In [72]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[6606  349]
 [ 362 5308]]

In [73]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95      6955
           1       0.94      0.94      0.94      5670

    accuracy                           0.94     12625
   macro avg       0.94      0.94      0.94     12625
weighted avg       0.94      0.94      0.94     12625

In [74]:
news = "NASA announced that dinosaurs have been successfully cloned and will be released into national parks next month."

news_vector = tfidf.transform([news])

print(model.predict(news_vector))

[1]

In [75]:
print(df[df["label"] == 0][["title", "text"]].iloc[0])
print("--------------------------------")
print(df[df["label"] == 1][["title", "text"]].iloc[0])

title    Bobby Jindal, raised Hindu, uses story of Chri...
text     A dozen politically active pastors came here f...
Name: 3, dtype: str
--------------------------------
title    LAW ENFORCEMENT ON HIGH ALERT Following Threat...
text     No comment is expected from Barack Obama Membe...
Name: 0, dtype: str

In [76]:
news = "The Prime Minister met the President to discuss the national budget."

vector = tfidf.transform([news])

print(model.predict(vector))

[0]

In [77]:
news = "Aliens have taken control of the White House and dinosaurs will vote in the next election."

vector = tfidf.transform([news])

print(model.predict(vector))

[1]

In [78]:
news = "The Earth will disappear tomorrow according to NASA scientists."

vector = tfidf.transform([news])

print(model.predict(vector))

[1]

In [79]:
news = "The Prime Minister met the President to discuss the national budget and economic reforms. Officials said the meeting focused on improving infrastructure, employment, and healthcare."

print("Original Prediction:", model.predict(tfidf.transform([news])))

clean = preprocess_text(news)

print("Cleaned Text:", clean)

print("After Preprocessing:", model.predict(tfidf.transform([clean])))

Original Prediction: [0]
Cleaned Text: prime minist met presid discuss nation budget econom reform offici said meet focus improv infrastructur employ healthcar
After Preprocessing: [0]

In [80]:
import pandas as pd

df = pd.read_csv("../data/WELFake_Dataset.csv")

print(df["label"].value_counts())

label
1    37106
0    35028
Name: count, dtype: int64

In [81]:
print(df[df["label"] == 0][["title", "text"]].head(3))
print("----------------------------------")
print(df[df["label"] == 1][["title", "text"]].head(3))

                                                title  \
3   Bobby Jindal, raised Hindu, uses story of Chri...
11  May Brexit offer would hurt, cost EU citizens ...
12  Schumer calls on Trump to appoint official to ...

                                                 text
3   A dozen politically active pastors came here f...
11  BRUSSELS (Reuters) - British Prime Minister Th...
12  WASHINGTON (Reuters) - Charles Schumer, the to...
----------------------------------
                                               title  \
0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...
1                                                NaN
2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...

                                                text
0  No comment is expected from Barack Obama Membe...
1     Did they post their votes for Hillary already?
2   Now, most of the demonstrators gathered last ...

In [82]:
news = "Reserve Bank of India kept the repo rate unchanged after reviewing inflation and economic growth."

clean = preprocess_text(news)

print(clean)

print(model.predict(tfidf.transform([clean])))

reserv bank india kept repo rate unchang review inflat econom growth
[1]

In [83]:
news = "Aliens have taken control of the White House and dinosaurs will vote in the next election."

clean = preprocess_text(news)

print(clean)

print(model.predict(tfidf.transform([clean])))

alien taken control white hous dinosaur vote next elect
[1]

In [84]:
# Actual REAL news from your dataset
real_samples = df[df["label"] == 0][["title", "text"]].sample(5)

for i, row in real_samples.iterrows():
    news = str(row["title"]) + " " + str(row["text"])
    clean = preprocess_text(news)
    pred = model.predict(tfidf.transform([clean]))[0]

    print("\nACTUAL LABEL: 0 (REAL)")
    print("MODEL PREDICTION:", pred)
    print("NEWS:", news[:500])
    print("-" * 80)

ACTUAL LABEL: 0 (REAL)
MODEL PREDICTION: 0
NEWS: Former Uzbek leader's daughter to resign as ambassador SAMARKAND, Uzbekistan (Reuters) - Lola Karimova-Tillyaeva, the second daughter of Uzbek president Islam Karimov who died last year, will step down soon as Uzbekistan s representative at UNESCO, she said on Monday. Karimova-Tillyaeva, 39, said she would focus on helping run a charitable foundation named after her father who died last September after running the ex-Soviet Central Asian state with an iron fist for 27 years.  In the near future,
--------------------------------------------------------------------------------

ACTUAL LABEL: 0 (REAL)
MODEL PREDICTION: 0
NEWS: Four dead in ambush of World Food Programme convoy in Nigeria BAUCHI, Nigeria (Reuters) - Four people were killed when a United Nations World Food Programme (WFP) aid convoy was ambushed in northeast Nigeria, a WFP spokeswoman said on Sunday, in the latest attack in the region as the conflict with Boko Haram nears its ninth year. Attacks on aid workers are relatively rare in the conflict with the Islamist insurgency, compared with assaults on the military and civilians in Nigeria s northeast. Th
--------------------------------------------------------------------------------

ACTUAL LABEL: 0 (REAL)
MODEL PREDICTION: 0
NEWS: U.S. Interior Dept. watchdog launches probe into Zinke's travel WASHINGTON (Reuters) - The Interior Department’s watchdog agency has launched an investigation into Secretary Ryan Zinke’s travels after reports emerged last week that he had used a private plane owned by an oil executive, the inspector general’s office said on Monday.  The Inspector General (IG) opened an investigation on Friday after receiving numerous complaints on Thursday about Zinke’s travels, including the use of three charte
--------------------------------------------------------------------------------

ACTUAL LABEL: 0 (REAL)
MODEL PREDICTION: 0
NEWS: U.S. State Department questions Gulf motives on Qatar boycott WASHINGTON (Reuters) - The U.S. State Department bluntly questioned on Tuesday the motives of Saudi Arabia and the United Arab Emirates for their boycott of Doha, saying it was “mystified” the Gulf states had not released their grievances over Qatar. In Washington’s strongest language yet on the Gulf dispute, the State Department said the more time goes by, “the more doubt is raised about the actions taken by Saudi Arabia and the UAE.
--------------------------------------------------------------------------------

ACTUAL LABEL: 0 (REAL)
MODEL PREDICTION: 1
NEWS: Benghazi: The fundamental question that still hasn't been answered The Benghazi Committee set out to investigate why four Americans died in Benghazi September 11, 2012, not to damage a presidential candidate. Rightly or wrongly, their credibility has been called into question, including by statements from fellow Republicans.

What I’ll be watching for on Thursday is not questions about Hillary Clinton’s emails; but the fundamental question:  What were the Americans doing in Benghazi in the first
--------------------------------------------------------------------------------

In [85]:
fake_samples = df[df["label"] == 1][["title", "text"]].sample(5)

for i, row in fake_samples.iterrows():

    news = str(row["title"]) + " " + str(row["text"])

    clean = preprocess_text(news)

    pred = model.predict(
        tfidf.transform([clean])
    )[0]

    print("\nACTUAL LABEL: 1 (FAKE)")
    print("MODEL PREDICTION:", pred)
    print("NEWS:", news[:500])
    print("-" * 80)

ACTUAL LABEL: 1 (FAKE)
MODEL PREDICTION: 1
NEWS: Bayern Munich beat Augsburg 3-1 News Bulletin Bayern Munich players celebrate after Philipp Lahm scored the opening goal during the German Cup DFB Pokal second round football match FC Bayern Munich v FC Augsburg in Munich, southern Germany on October 26, 2016. (AFP)
German Cup holders Bayern Munich have sealed a spot in the third round of the DFB Pokal after beating Augsburg 3-1.
Veteran defender Philipp Lahm scored the opener for Bayern after only two minutes into the game. Julian Green then
--------------------------------------------------------------------------------

ACTUAL LABEL: 1 (FAKE)
MODEL PREDICTION: 1
NEWS: BREAKING : New Poll Shows Trump is About to TAKE MICHIGAN! – TruthFeed BREAKING : New Poll Shows Trump is About to TAKE MICHIGAN! BREAKING : New Poll Shows Trump is About to TAKE MICHIGAN! Breaking News By Amy Moreno November 2, 2016
They call Michigan a “Brexit” state – along with Ohio, Pennsylvania, and Wisconsin.
The states that can change it all and send the evil globalists packing.
Michael Moore, a Hillary supporter, and a Michigan native is on the ground talking to people, and he sees t
--------------------------------------------------------------------------------

ACTUAL LABEL: 1 (FAKE)
MODEL PREDICTION: 1
NEWS: NEW AUDIO RELEASED Moments After Muslim SOMALI-IMMIGRANT Cop Shot and Killed 40-Yr Old ‘Bride-to-Be” Somali immigrant and Minnesota police officer Mohamed Noor shot and killed a 40 yr. old Australian woman when they arrived at her home to respond to a call she made about a potential sexual assault near her home. Officer Noor has only been a police officer for 2 years, and although he is celebrated by the local mayor for being a Somali immigrant, he is no stranger to controversy. He currently has
--------------------------------------------------------------------------------

ACTUAL LABEL: 1 (FAKE)
MODEL PREDICTION: 1
NEWS: WATCH: COWARDLY ANTIFA THUGS Surround Afghanistan Veteran At Boston Free Speech Rally…Scream In His Face: “F*ck Off Nazi Scum!” ***WARNING***This video is very disturbing!Try to imagine this brave man who voluntarily enlisted in our US military, traveled halfway around the world to Afghanistan where he risked his life to defend our nation against some of the most evil people on the planet, only to come home to some of the most evil people in America shouting,  F*ck off Nazi scum!  in his face. T
--------------------------------------------------------------------------------

ACTUAL LABEL: 1 (FAKE)
MODEL PREDICTION: 1
NEWS: Light Language Activation by Lightstar – Arcturus and Arcturian Starseed [VIDEO] Click Here To Learn More About Alexandra's Personalized Essences Psychic Protection Click Here for More Information on Psychic Protection! Implant Removal Series Click here to listen to the IRP and SA/DNA Process Read The Testimonials Click Here To Read What Others Are Experiencing! Copyright © 2012 by Galactic Connection. All Rights Reserved.
Excerpts may be used, provided that full and clear credit is given to Al
--------------------------------------------------------------------------------